export const albums = [
  [
    {
      id: 1,
      title: 'Phố không em',
      artist: 'Thái Đinh',
      audioSrc: require('./assets/PhoKhongEm-Thai Dinh.mp3'),
      image: 'https://avatar-ex-swe.nixcdn.com/song/2019/03/15/6/8/d/a/1552622453522_640.jpg',
      duration: '4:40',
    },
    {
      id: 2,
      title: 'Đi qua mùa hạ',
      artist: 'Thái Đinh',
      audioSrc: require('./assets/DiQuaMuaHa.mp3'),
      image: 'https://avatar-ex-swe.nixcdn.com/song/2019/07/19/3/8/8/f/1563500239222_640.jpg',
      duration: '4:43',
    },
    {
      id: 3,
      title: 'Em còn dùng số này không',
      artist: 'Shayne Ward',
      audioSrc: require('./assets/Until You - Shayne Ward.mp3'),
      image: 'https://i.ytimg.com/vi/WP-GRECzAKU/maxresdefault.jpg',
      duration: '4:08',
    },

    {
      id: 4,
      title: 'Bước qua nhau',
      artist: 'Vũ',
      audioSrc: require('./assets/Buoc Qua Nhau - Vu.mp3'),
      image: 'https://i.ytimg.com/vi/ixdSsW5n2rI/maxresdefault.jpg',
      duration: '4:17',
    },
    {
      id: 5,
      title: 'Happy for you',
      artist: 'Vũ',
      audioSrc: require('./assets/HappyForYou.mp3'),
      image: 'https://i.ytimg.com/vi/mf4upAPwHEo/maxresdefault.jpg',
      duration: '3:46',
    },
    {
      id: 6,
      title: 'Lạ lùng',
      artist: 'Vũ',
      audioSrc: require('./assets/La Lung - Vu.mp3'),
      image: 'https://i.ytimg.com/vi/F5tS5m86bOI/maxresdefault.jpg',
      duration: '4:21',
    },

    {
      id: 7,
      title: 'Bài này chill phết',
      artist: 'Đen Vâu',
      audioSrc: require('./assets/Bai Nay Chill Phet - Den_ Min.mp3'),
      image: 'https://i.ytimg.com/vi/ddaEtFOsFeM/maxresdefault.jpg',
      duration: '4:36',
    },
    {
      id: 8,
      title: 'Lối nhỏ',
      artist: 'Đen Vâu',
      audioSrc: require('./assets/Loi Nho - Den_ Phuong Anh Dao.mp3'),
      image: 'https://i.ytimg.com/vi/KKc_RMln5UY/maxresdefault.jpg',
      duration: '4:12',
    },
    {
      id: 9,
      title: 'Trốn tìm',
      artist: 'Đen Vâu',
      audioSrc: require('./assets/Tron Tim - Den_ MTV Band.mp3'),
      image: 'https://i.ytimg.com/vi/Ws-QlpSltr8/maxresdefault.jpg',
      duration: '4:08',
    },
  ],
  [
    {
      id: 10,
      title: 'Phố không em',
      artist: 'Thái Đinh',
      audioSrc: require('./assets/PhoKhongEm-Thai Dinh.mp3'),
      image: 'https://avatar-ex-swe.nixcdn.com/song/2019/03/15/6/8/d/a/1552622453522_640.jpg',
      duration: '4:40',
    },
    {
      id: 11,
      title: 'Đi qua mùa hạ',
      artist: 'Thái Đinh',
      audioSrc: require('./assets/DiQuaMuaHa.mp3'),
      image: 'https://avatar-ex-swe.nixcdn.com/song/2019/07/19/3/8/8/f/1563500239222_640.jpg',
      duration: '4:43',
    },
    {
      id: 12,
      title: 'Em còn dùng số này không',
      artist: 'Shayne Ward',
      audioSrc: require('./assets/Until You - Shayne Ward.mp3'),
      image: 'https://i.ytimg.com/vi/WP-GRECzAKU/maxresdefault.jpg',
      duration: '4:48',
    },
  ],
  [
    {
      id: 13,
      title: 'Bước qua nhau',
      artist: 'Vũ',
      audioSrc: require('./assets/Buoc Qua Nhau - Vu.mp3'),
      image: 'https://i.ytimg.com/vi/ixdSsW5n2rI/maxresdefault.jpg',
      duration: '4:07',
    },
    {
      id: 14,
      title: 'Happy for you',
      artist: 'Vũ',
      audioSrc: require('./assets/HappyForYou.mp3'),
      image: 'https://i.ytimg.com/vi/mf4upAPwHEo/maxresdefault.jpg',
      duration: '4:40',
    },
    {
      id: 15,
      title: 'Lạ lùng',
      artist: 'Vũ',
      audioSrc: require('./assets/La Lung - Vu.mp3'),
      image: 'https://i.ytimg.com/vi/F5tS5m86bOI/maxresdefault.jpg',
      duration: '4:08',
    },
  ],
  [
    {
      id: 16,
      title: 'Bài này chill phết',
      artist: 'Đen Vâu',
      audioSrc: require('./assets/Bai Nay Chill Phet - Den_ Min.mp3'),
      image: 'https://i.ytimg.com/vi/ddaEtFOsFeM/maxresdefault.jpg',
      duration: '4:17',
    },
    {
      id: 17,
      title: 'Lối nhỏ',
      artist: 'Đen Vâu',
      audioSrc: require('./assets/Loi Nho - Den_ Phuong Anh Dao.mp3'),
      image: 'https://i.ytimg.com/vi/KKc_RMln5UY/maxresdefault.jpg',
      duration: '4:46',
    },
    {
      id: 18,
      title: 'Trốn tìm',
      artist: 'Đen Vâu',
      audioSrc: require('./assets/Tron Tim - Den_ MTV Band.mp3'),
      image: 'https://i.ytimg.com/vi/Ws-QlpSltr8/maxresdefault.jpg',
      duration: '4:21',
    },
  ],
];
export const albumImg = [
  {
    albumName: 'Việt',
    albumImg: 'https://i.scdn.co/image/ab67616d00001e02d00091c35bafaa6837d8b6bf',
  },
  {
    albumName: 'Thái Đinh',
    albumImg: 'https://trixie.com.vn/media/images/article/76382490/unnamed%20(1).jpg',
  },
  {
    albumName: 'Vũ',
    albumImg: 'https://event.mediacdn.vn/2020/11/30/vu-p-16067234297342144615946.png',
  },
  {
    albumName: 'Đen Vâu',
    albumImg: 'https://static2.yan.vn/YanNews/2167221/201905/tieu-su-ca-si-den-vau-43ea68db.jpg',
  },
];
